name: lint

on:
	push:
		branches:
			- main

	pull_request:
		branches:
			- main

jobs:
	Build:
		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v2
		- uses: pnpm/action-setup@v2 # instalar pnpm utilizando o packagemanager em package.json

		- name: utilizar o node.js 18
			uses: actions/setup-node@v2
			with:
				node-version: 18
				cache: "pnpm"

		- name: instalar dependências
			run: pnpm install --frozen-lockfile

		- name: lint e teste caso compilado
			run: pnpm test